##
##  Makefile -- Build procedure for sample ifenv Apache module
##  Autogenerated via ``apxs -n ifenv -g''.
##

builddir=.
top_srcdir=/Users/hiroya/local/httpd-2.0.63
top_builddir=/Users/hiroya/local/httpd-2.0.63
include /Users/hiroya/local/httpd-2.0.63/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_ifenv.o mod_ifenv.lo mod_ifenv.slo mod_ifenv.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/ifenv

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

