/* 
**  mod_ifenv.c -- Apache sample ifenv module
**  [Autogenerated via ``apxs -n ifenv -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_ifenv.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /ifenv in as follows:
**
**    #   httpd.conf
**    LoadModule ifenv_module modules/mod_ifenv.so
**    <Location /ifenv>
**    SetHandler ifenv
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /ifenv and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/ifenv 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_ifenv.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

static const char *start_if_env(cmd_parms *cmd, void *dummy, const char *arg)
{
    const char *endp;
    int exists;
    int not = 0;

    endp = ap_strrchr_c(arg, '>');
    if (endp == NULL) {
        return unclosed_directive(cmd);
    }

    arg = apr_pstrndup(cmd->pool, arg, endp - arg);

    if (arg[0] == '!') {
        not = 1;
        arg++;
    }

    if((!not && getenv(arg)) || (not && !getenv(arg))) {
        ap_directive_t *parent = NULL;
        ap_directive_t *current = NULL;
        const char *retval;

        retval = ap_build_cont_config(cmd->pool, cmd->temp_pool, cmd,
                                      &current, &parent, "<IfEnv");
        *(ap_directive_t **)dummy = current;
        return retval;
    }
    else {
        *(ap_directive_t **)dummy = NULL;
        return ap_soak_end_container(cmd, "<IfEnv");
    }
}

static const command_rec ifenv_directive_cmds[] =
{
    AP_INIT_TAKE1("<IfEnv", start_if_env, NULL, EXEC_ON_READ | RSRC_CONF,
                  "Container for directives based on existance of env variable"),
    NULL,
};

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA ifenv_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    ifenv_directive_cmds,  /* table of config file commands       */
    NULL,  /* register hooks                      */
};

